kafka:
    group:
        id: app.1
    producer:
        id: producer.1
    request:
        topic: requestTopic
    response:
        topic: responseTopic
    server: localhost:9092
server:
    port: 9997
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration